name: App Build

on:
  push:
    branches: [main]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            target: linux
          - os: windows-latest
            target: win

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install ElectronNET.CLI
        run: dotnet tool install ElectronNET.CLI -g

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: cd src/Mycropad.App && npm install

      - name: Create the app package
        shell: bash
        working-directory: src/Mycropad.App
        run: electronize build /target $target
        env:
          target: ${{ matrix.target }}

      - name: Archive Linux artifacts
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: snap
          path: |
            src/Mycropad.App/bin/Desktop/*.snap

      - name: Archive Linux artifacts
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: build-linux
          path: |
            src/Mycropad.App/bin/Desktop/linux-unpacked/

      - name: Archive Windows artifacts
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'windows')
        with:
          name: build-win
          path: |
            src/Mycropad.App/bin/Desktop/win-unpacked/
