name: App Build

on:
  push:
    branches: [main]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            target: linux
          - os: windows-latest
            target: win

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install ElectronNET.CLI
        run: dotnet tool install ElectronNET.CLI -g

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: cd src/Mycropad.App && npm install

      - name: Linux build
        if: startsWith(matrix.os, 'ubuntu')
        working-directory: src/Mycropad.App
        run: electronize build /target $ELECTRON_TARGET
        env:
          ELECTRON_TARGET: ${{ matrix.target }}

      - name: Windows build
        if: startsWith(matrix.os, 'windows')
        working-directory: src/Mycropad.App
        run: electronize build /target $Env:ELECTRON_TARGET
        env:
          ELECTRON_TARGET: ${{ matrix.target }}

      - name: Archive Snap
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: snap
          path: |
            src/Mycropad.App/bin/Desktop/*.snap

      - name: Archive Windows setup
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'windows')
        with:
          name: Windows setup
          path: |
            src/Mycropad.App/bin/Desktop/*Setup*.exe
